version: '3'

services:
  movie:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: themoviesharing
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
